name: 'Build Storybook'
on: workflow_call
jobs:
    storybook-build:
        name: 'Building Storybook'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Build Storybook
              run: npm run build-storybook
