name: 'Tests and deployment'
on:
    push:
        branches:
            - main
    pull_request:
        types:
            - ready_for_review
jobs:
    call-storybook-build:
        uses: ./build-storybook.yml
    call-interactions-and-accessibility-tests:
        uses: ./interactions-and-accessibility-tests.yml
    call-deploy-storybook-on-chromatic:
        needs:
            - call-storybook-build
            - call-interactions-and-accessibility-tests
        uses: ./deploy-storybook.yml
        secrets:
            chromaticToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
