name: 'Deploy Storybook'
on:
    workflow_call:
        secrets:
            chromaticToken:
                required: true
jobs:
    deploy-on-chromatic:
        name: 'Deploying Storybook on Chromatic'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install dependencies
              run: npm ci
            - name: Publish to Chromatic
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.chromaticToken }}
