name: 'Tests'
on:
    push:
        branches-ignore:
            - main
jobs:
    call-storybook-build:
        uses: ./.github/workflows/build-storybook.yml
    call-interactions-and-accessibility-tests:
        uses: ./.github/workflows/interactions-and-accessibility-tests.yml
